FROM python:3

WORKDIR /usr/src/app

EXPOSE 8030

# COPY requirements.txt ./
RUN pip install fastapi[standard] ollama langchain chromadb pdfplumber
RUN pip install -U langchain-community

# COPY . .

CMD ["/bin/bash", "-c", "fastapi dev ./main.py --port 8080 --host 0.0.0.0 " ]
# CMD ["/bin/bash", "-c", "python ./main.py" ]