FROM python:3

WORKDIR /usr/src/app

EXPOSE 8030

# COPY requirements.txt ./
RUN pip install fastapi[standard] langchain-ollama langchain_community langchain_experimental pdfplumber langchain-huggingface faiss-cpu

# COPY . .

CMD ["/bin/bash", "-c", "fastapi dev ./main.py --port 8080 --host 0.0.0.0 > log.out" ]
# CMD ["/bin/bash", "-c", "python ./main.py > log.out" ]