FROM python:3

WORKDIR /usr/src/app

EXPOSE 8030

# COPY requirements.txt ./
RUN pip install "fastapi[standard]"

COPY . .

# CMD ["/bin/bash", "-c", "echo 'test'"]
# CMD ["/bin/bash", "-c", "fastapi dev ./main.py --port 8030 --host 127.0.0.1" ]
CMD ["/bin/bash", "-c", "python ./main.py > log.out" ]