version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/http.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/var/www/letsencrypt:rw
    depends_on:
      - node

  node:
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    build: .
    depends_on:
      - mongo

volumes:
  mongo-data: